apache/rocketmq-dashboard

src/main/resources/static/src/ops.js, src/main/resources/static/view/pages/ops.html
#22
Use md-chips of Angular Material instead of input elements,each namesrv address is an md-chip element that is easy to add and remove.
=> [ISSUE #22]Optimizing the ops page.

src/main/java/org/apache/rocketmq/dashboard/controller/ConsumerController.java, src/main/java/org/apache/rocketmq/dashboard/service/ConsumerService.java, src/main/java/org/apache/rocketmq/dashboard/service/impl/ConsumerServiceImpl.java, src/main/resources/static/src/consumer.js, src/main/resources/static/view/pages/consumer.html, src/main/resources/static/view/pages/message.html, src/main/resources/static/view/pages/messageTrace.html, src/main/resources/static/view/pages/topic.html, src/test/java/org/apache/rocketmq/dashboard/controller/ConsumerControllerTest.java, src/test/java/org/apache/rocketmq/dashboard/util/MockObjectUtil.java
#25 
1、add filter
2、page optimization
XX
XXXX
=> [ISSUE #25]Add filter in consumer list.

pom.xml, src/main/java/org/apache/rocketmq/dashboard/controller/DlqMessageController.java, src/main/java/org/apache/rocketmq/dashboard/model/DlqMessageExcelModel.java, src/main/java/org/apache/rocketmq/dashboard/service/DlqMessageService.java, src/main/java/org/apache/rocketmq/dashboard/service/impl/DlqMessageServiceImpl.java, src/main/java/org/apache/rocketmq/dashboard/util/ExcelUtil.java, src/main/resources/application.properties, src/main/resources/static/index.html, src/main/resources/static/src/app.js, src/main/resources/static/src/dlqMessage.js, src/main/resources/static/src/i18n/en.js, src/main/resources/static/src/i18n/zh.js, src/main/resources/static/view/layout/_header.html, src/main/resources/static/view/pages/consumer.html, src/main/resources/static/view/pages/dlqMessage.html, src/test/java/org/apache/rocketmq/dashboard/controller/DlqMessageControllerTest.java
#30 
1、Support consumerIGroup+ time range query and consumerGroup+msgId for precise query, resend the dead letter message, so that consumers can re-consume, if the user cannot handle the dead letter message, can export it in order to avoid the expiration date.
XX
XXXX
=> [ISSUE #30]Added DLQ message management

src/main/java/org/apache/rocketmq/dashboard/config/AuthWebMVCConfigurerAdapter.java, src/test/java/org/apache/rocketmq/dashboard/config/AuthWebMVCConfigurerAdapterTest.java
add Html router for front-end
add view controllers, all URI with suffix htm will be redirected to app.html
=> [ISSUE #28] add Html router for front-end

pom.xml, src/main/java/org/apache/rocketmq/dashboard/service/client/MQAdminExtImpl.java, src/main/java/org/apache/rocketmq/dashboard/service/impl/TopicServiceImpl.java, src/test/java/org/apache/rocketmq/dashboard/admin/MQAdminExtImplTest.java
=> [ISSUE #38]update rocketmq version.

src/main/java/org/apache/rocketmq/dashboard/service/client/MQAdminExtImpl.java, src/main/java/org/apache/rocketmq/dashboard/service/impl/ConsumerServiceImpl.java, src/test/java/org/apache/rocketmq/dashboard/admin/MQAdminExtImplTest.java
=> [ISSUE #42]Fix deleteSubscriptionGroup not remove consumer offset.

src/main/java/org/apache/rocketmq/dashboard/service/impl/MessageServiceImpl.java, src/main/java/org/apache/rocketmq/dashboard/service/impl/MessageTraceServiceImpl.java, src/main/resources/static/src/message.js, src/main/resources/static/view/pages/message.html, src/test/java/org/apache/rocketmq/dashboard/controller/MessageTraceControllerTest.java
=> [ISSUE #43]Give a tip when no message found with topic + time query.

src/main/java/org/apache/rocketmq/dashboard/service/impl/MessageServiceImpl.java
Fix a BUG when query messge by topic
=> [ISSUE #48] Fix query message bug

src/main/java/org/apache/rocketmq/dashboard/controller/DashboardController.java, src/main/java/org/apache/rocketmq/dashboard/controller/DlqMessageController.java, src/main/java/org/apache/rocketmq/dashboard/controller/NamesvrController.java, src/main/resources/role-permission.yml, src/main/resources/static/src/dlqMessage.js, src/main/resources/static/src/remoteApi/remoteApi.js, src/test/java/org/apache/rocketmq/dashboard/controller/DashboardControllerTest.java, src/test/java/org/apache/rocketmq/dashboard/controller/DlqMessageControllerTest.java, src/test/java/org/apache/rocketmq/dashboard/controller/NamesvrControllerTest.java
Update `role-permission.yml` default value to make RocketMQ-Dashboard easier to use.
Update `role-permission.yml` default value so that normal users can have read permission by default.
local test succeed, normal user can access all read URI.
=> [ISSUE #48] Fix Normal User login after to tips:no permission

src/main/java/org/apache/rocketmq/dashboard/controller/DlqMessageController.java, src/main/resources/role-permission.yml, src/main/resources/static/src/dlqMessage.js, src/test/java/org/apache/rocketmq/dashboard/controller/DlqMessageControllerTest.java
Modify the suffix of the interface. The query type is .query and the operation type is .do
XX
XXXX
=> [ISSUE #50]Modify the suffix of the interface name.

pom.xml, src/test/java/org/apache/rocketmq/dashboard/controller/DlqMessageControllerTest.java
=> [ISSUE #60]Update SpringBoot version.

src/main/resources/static/src/message.js, src/main/resources/static/view/pages/message.html
=> [ISSUE #54]Add filtering function when querying message consumption.

src/main/java/org/apache/rocketmq/dashboard/config/AuthWebMVCConfigurerAdapter.java
Configure the dlq message interface path in the authInterceptor
XX
XXXX
=> Configure the dlq message interface path in the authInterceptor

src/main/resources/static/src/dlqMessage.js
=> [ISSUE #72]The batchResend and batchExport buttons are disabled when there is no dlq message

src/main/java/org/apache/rocketmq/dashboard/admin/MQAdminFactory.java, src/main/java/org/apache/rocketmq/dashboard/config/CollectExecutorConfig.java, src/main/java/org/apache/rocketmq/dashboard/task/CollectTaskRunnble.java, src/main/java/org/apache/rocketmq/dashboard/task/DashboardCollectTask.java, src/main/resources/application.yml, src/main/resources/logback.xml, src/test/java/org/apache/rocketmq/dashboard/config/CollectExecutorConfigTest.java, src/test/java/org/apache/rocketmq/dashboard/task/DashboardCollectTaskTest.java
=> [ISSUE #68]Use multithreading for topic data collection in collectTask

pom.xml
=> [ISSUE #74]upgrade rocketmq version to 4.9.3

src/test/java/org/apache/rocketmq/dashboard/controller/TopicControllerTest.java
[Issue #119](https://github.com/apache/rocketmq-dashboard/issues/119)
[Issue #119](https://github.com/apache/rocketmq-dashboard/issues/119)
=> [ISSUE #119] Fix flaky test in TopicControllerTest.java

src/main/resources/logback.xml
=> [ISSUE #111] Update log name

src/main/java/org/apache/rocketmq/dashboard/service/impl/ConsumerServiceImpl.java, src/test/java/org/apache/rocketmq/dashboard/controller/ConsumerControllerTest.java
#123 
Using multi-threading optimization, the optimized interface call time is less than 1s
=> [ISSUE #123]Optimize groupList.query

docs/1_0_0/UserGuide_CN.md, docs/1_0_0/UserGuide_EN.md
1. Supplement userGuide.md for RocketMQ 5.0 in en & cn
=> Supplement UserGuide for RocketMQ 5.0

src/main/resources/static/src/topic.js
=> fix:Fixed the issue that normal messages in version v4 are not showed

src/main/resources/static/src/i18n/en.js, src/main/resources/static/src/i18n/zh.js, src/main/resources/static/src/topic.js, src/main/resources/static/view/pages/topic.html
Support unspecified topic Add, Update and Query
支持未指定topic类型的新增、更新和查询功能
=> Support Unspecified Topic Add & Update & Query

src/main/java/org/apache/rocketmq/dashboard/service/client/MQAdminExtImpl.java
Due to changes in the message ID generation rules in the 5.x SDK, the timestamp in the message ID is parsed incorrectly when querying message details on the dashboard. This leads to the inability to retrieve message details. The dashboard code needs to be modified to accommodate this scenario.
[[issues-7114]](https://github.com/apache/rocketmq/issues/7114)
[[issues-64]](https://github.com/apache/rocketmq-dashboard/issues/64)
Changed the message querying logic that parses the timestamp to use the `queryMessage` method provided by `MQAdminExt`.
Verified by connecting to the MQ cluster.
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the …
=> fix: 5.x query message detail throw: Failed to query message by Id: xxx

src/main/java/org/apache/rocketmq/dashboard/service/impl/MessageServiceImpl.java
duplicate message in the topic tab message list in the message menu for rocketmq5.x
=> [ISSUE #169] duplicate message in the topic tab message list in the message menu for rocketmq5.x 

pom.xml, src/main/java/org/apache/rocketmq/dashboard/task/CollectTaskRunnble.java
remove rocketmq-broker dependency
XX
XXXX
=> remove rocketmq-broker dependency

pom.xml
remove rocketmq-namesrv dependency
=> remove rocketmq-namesrv dependency

src/main/resources/static/src/consumer.js, src/main/resources/static/src/controller.js, src/main/resources/static/src/topic.js
bug fix, v5 check will always be true, can't set to v4
fixes #268 
'false' convert to be false nto true
=> [ISSUE #268] front js check is v5 'false' will be true fix (界面切换v4后topic列不出来)

src/main/java/org/apache/rocketmq/dashboard/service/impl/MessageServiceImpl.java, src/main/java/org/apache/rocketmq/dashboard/service/impl/TopicServiceImpl.java, src/main/java/org/apache/rocketmq/dashboard/support/AutoCloseConsumerWrapper.java, src/test/java/org/apache/rocketmq/dashboard/util/AutoCloseConsumerWrapperTests.java
The purpose of this submission is to optimize the message and topic query interfaces. By reasonably reusing already created resources, the response time of the interfaces is reduced from 3-5 seconds to within 50 milliseconds. Additionally, by leveraging a thread pool and tasks, the destruction of DefaultMQConsumer resources is controlled, with a default setting to automatically destroy after 1 minute of inactivity.
- Modified the creation/destruction logic for Consumers and Producers in MessageServiceImpl and TopicServiceImpl
- Added AutoCloseConsumerWrapper class to manage Consumer lifecycle and prevent prolonged connections
- Implemented AutoCloseConsumerWrapperTests to validate the new functionality
- Passed all integration and unit tests (except for a few mock data issues)
Follow this …
=> pref: optimize the response speed of the query api

.gitignore, src/test/java/org/apache/rocketmq/dashboard/admin/MQAdminExtImplTest.java, src/test/java/org/apache/rocketmq/dashboard/controller/ConsumerControllerTest.java, src/test/java/org/apache/rocketmq/dashboard/controller/MessageControllerTest.java, src/test/java/org/apache/rocketmq/dashboard/controller/TopicControllerTest.java, src/test/java/org/apache/rocketmq/dashboard/service/impl/MessageServiceImplTest.java, src/test/java/org/apache/rocketmq/dashboard/service/impl/TopicServiceImplTest.java
- Adding more unit tests and increase the code coverage for better time migrating and refactoring the dashboard to Spring Boot 3 and Java 17.
- This is only one part of work for the issue #266.
- Added 22 unit tests. Improved code coverage rate from 74% to 80%. 
- Fixed all 6 originally failing tests. 
- Passed all integration and unit tests.
=> Fixing and Adding Unit Tests (#266)

src/main/java/org/apache/rocketmq/dashboard/service/client/MQAdminExtImpl.java
fix #274 
By examining the call stack of the method where the bug occurred, it was discovered that the method automatically adds a time window of 3 days. Messages older than 3 days couldn't be found.
Therefore, we decided to keep the existing cluster-name-based query design, but revert to the original implementation using reflection to call the queryMessage method (since the time-parameter-specific method isn't exposed in the interface, making reflection necessary).
After the change，the bug is fixed
=> [ISSUE #274] fix:Failed to find messages older than 3 days using message ID

src/main/resources/static/style/app.css, src/main/resources/static/view/layout/_header.html
=> [issues #279] fix: align top navigation bar styles 

src/main/java/org/apache/rocketmq/dashboard/controller/ConsumerController.java, src/main/java/org/apache/rocketmq/dashboard/service/ConsumerService.java, src/main/java/org/apache/rocketmq/dashboard/service/impl/ConsumerServiceImpl.java, src/main/resources/static/src/consumer.js, src/main/resources/static/view/pages/consumer.html
fix #290 
Add global refresh back
XXXX
=> fix: Add consumer global refresh and fix the problem

src/main/java/org/apache/rocketmq/dashboard/service/impl/ConsumerServiceImpl.java, src/main/java/org/apache/rocketmq/dashboard/service/impl/TopicServiceImpl.java
fix #295 
Cache the address of each topic at the same time during global refresh, and then return it during a single refresh
XXXX
=> fix: Solve the null pointer after a single refresh of the consumer #295

frontend-new/public/index.html, frontend-new/src/pages/Acl/acl.jsx, src/main/java/org/apache/rocketmq/dashboard/service/impl/AclServiceImpl.java
fix #315 
When entering the page, first select the cluster and brokerName, and then perform an acl query for a specific machine.
XXXX
=> [ISSUES #315]: Add acl2.0 cluster support

pom.xml
=> [ISSUES#323]: fix Maven packaging error

frontend-new/README.md
=> #docs fix wrong port

src/main/java/org/apache/rocketmq/dashboard/aspect/admin/MQAdminAspect.java
=> [ISSUE #346] fix request error when logging in using the configuration file

pom.xml
According to the [documentation](https://projectlombok.org/setup/maven):
> To set up lombok with any build tool, you have to specify that the lombok dependency is required to compile your source code, but does not need to be present when running/testing/jarring/otherwise deploying your code. Generally this is called a 'provided' dependency.
Use `provided` scope for `lombok`
Build locally without issue.
=> Use `provided` scope for `lombok`

frontend-new/src/api/remoteApi/remoteApi.js, frontend-new/src/components/consumer/ClientInfoModal.jsx, frontend-new/src/components/consumer/ConsumerDetailModal.jsx, frontend-new/src/components/consumer/DeleteConsumerModal.jsx, frontend-new/src/i18n/index.js, frontend-new/src/pages/Consumer/consumer.jsx, src/main/java/org/apache/rocketmq/dashboard/service/impl/ConsumerServiceImpl.java
=> [ISSUE #348] fix Some interaction issues with the consumer interface
